language: go
dist: xenial
before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3-venv
  - . ./start_test_environment.sh

# safelist Master branch changes only
branches:
  only:
    - master

after_success:
  - go build goflow.go
  - tar -czf goflow.Linux.AMD64.tar.gz goflow config_example.yml

after_failure:
  - cd aws-cli-tools
  - aws ec2 stop-instances --instance-id $AWS_INSTANCE_ID

deploy:
  provider: releases
  api_key: $api_token
  file: goflow.Linux.AMD64.tar.gz
  skip_cleanup: true
  on:
    tags: true