#
# Travis CI build script
# Runs on commits to the Master branch
# Tagged commits (vx.xx) will generate a new release.
# start_test_environment.sh contains more documentation about the building blocks required for this to work.
#
language: go
dist: xenial

branches:
  only:
  - master
  - /^v.*/

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python3-venv
  - . ./start_test_environment.sh

after_success:
  - cd aws-cli-tools
  - aws ec2 stop-instances --instance-id $AWS_INSTANCE_ID
  - cd ..
  - go build goflow.go
  - tar -czf goflow.Linux.AMD64.tar.gz goflow config_example.yml

after_failure:
  - cd aws-cli-tools
  - aws ec2 stop-instances --instance-id $AWS_INSTANCE_ID

deploy:
  provider: releases
  api_key: $api_token
  file: goflow.Linux.AMD64.tar.gz
  skip_cleanup: true
  on:
    tags: true