backends:
  rdssql:
    type: timescale
    config:
      SQL_SERVER: ec2-13-239-40-194.ap-southeast-2.compute.amazonaws.com
      SQL_USERNAME: remoteuser
      #SQL_SERVER: 52.62.226.159
      #SQL_USERNAME: testgoflow
      SQL_DB: testgoflow

  kafka:
    type: kafka
    config:
      KAFKA_SERVER: ec2-13-210-246-197.ap-southeast-2.compute.amazonaws.com:9093
      SSL: true
      SSL_VERIFY: false
      TOPIC: test

frontends:
  netflow:
    config:
      bindaddr: 192.168.1.158
      bindport: 9999
    backend: rdssql

utilities:
  max_age: 180

api: 127.0.0.1:8880
