backends:
  rdssql:
    type: mysql
    config:
      SQL_SERVER: 52.62.226.159
      SQL_USERNAME: testgoflow
      SQL_DB: testgoflow
  dumper:
    type: dump
    config:
frontends:
  netflow:
    config:
      bindaddr: 192.168.1.164
      bindport: 9999
    backend: rdssql
