backends:
  rdssql:
    type: timescale
    config:
      SQL_SERVER: ec2-13-211-228-101.ap-southeast-2.compute.amazonaws.com
      SQL_USERNAME: remoteuser
      #SQL_SERVER: 52.62.226.159
      #SQL_USERNAME: testgoflow
      SQL_DB: testgoflow
  dumper:
    type: dump
    config:
frontends:
  netflow:
    config:
      bindaddr: 192.168.1.164
      bindport: 9999
    backend: rdssql
