### Goflow Configuration file
### Backend configuration
###
backends:
  # Key is the identifying name
  rdssql:
    # Currently supported types:
    # - mysql
    # - timescale
    # - dumper
    type: mysql
    config:
      SQL_SERVER: your-sql-server.com
      SQL_USERNAME: your-sql-username
      SQL_DB: your-database-name
      # SQL_PASSWORD can be specified here but preferably, set it in the environment
  dumper:
    type: dump
    config:
  # Kafka example
  kafka:
    type: kafka
    config:
      # Required
      KAFKA_SERVER: [your-server]:[listening-port]
      KAFKA_TOPIC: [your-topic]
      # Optional
      SASL_USER: [SASL User]
      SSL: true
      SSL_VERIFY: false

###
### Frontend config
###
frontends:
  netflow:
    config:
      # Bindaddr: IP address on local system to listen for netflow
      bindaddr: [local address]
      # Bindport: Port to listen on
      bindport: [local port]
    # Backend to store data received by this frontend
    backend: rdssql

###
### API config
###
# Specify bindaddr for API
api: 127.0.0.1:8880

###
### Utility Config
###
utilities:
  # Max_age is the length of time - in days - to store flow records for. Flows are pruned one daily based on this number.
  max_age: 180